<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            ['code' => 'AF', 'country_enName' => 'Afghan', 'country_arName' => 'أفغانستان', 'country_enNationality' => 'Afghanistan', 'country_arNationality' => 'أفغانستاني'],
            ['code' => 'AL', 'country_enName' => 'Albania', 'country_arName' => 'ألبانيا', 'country_enNationality' => 'Albanian', 'country_arNationality' => 'ألباني'],
            ['code' => 'AX', 'country_enName' => 'Aland Islands', 'country_arName' => 'جزر آلاند', 'country_enNationality' => 'Aland Islander', 'country_arNationality' => 'آلاندي'],
            ['code' => 'DZ', 'country_enName' => 'Algeria', 'country_arName' => 'الجزائر', 'country_enNationality' => 'Algerian', 'country_arNationality' => 'جزائري'],
            ['code' => 'AS', 'country_enName' => 'American Samoa', 'country_arName' => 'ساموا-الأمريكي', 'country_enNationality' => 'American Samoan', 'country_arNationality' => 'أمريكي سامواني'],
            ['code' => 'AD', 'country_enName' => 'Andorra', 'country_arName' => 'أندورا', 'country_enNationality' => 'Andorran', 'country_arNationality' => 'أندوري'],
            ['code' => 'AO', 'country_enName' => 'Angola', 'country_arName' => 'أنغولا', 'country_enNationality' => 'Angolan', 'country_arNationality' => 'أنقولي'],
            ['code' => 'AI', 'country_enName' => 'Anguilla', 'country_arName' => 'أنغويلا', 'country_enNationality' => 'Anguillan', 'country_arNationality' => 'أنغويلي'],
            ['code' => 'AQ', 'country_enName' => 'Antarctica', 'country_arName' => 'أنتاركتيكا', 'country_enNationality' => 'Antarctican', 'country_arNationality' => 'أنتاركتيكي'],
            ['code' => 'AG', 'country_enName' => 'Antigua and Barbuda', 'country_arName' => 'أنتيغوا وبربودا', 'country_enNationality' => 'Antiguan', 'country_arNationality' => 'بربودي'],
            ['code' => 'AR', 'country_enName' => 'Argentina', 'country_arName' => 'الأرجنتين', 'country_enNationality' => 'Argentinian', 'country_arNationality' => 'أرجنتيني'],
            ['code' => 'AM', 'country_enName' => 'Armenia', 'country_arName' => 'أرمينيا', 'country_enNationality' => 'Armenian', 'country_arNationality' => 'أرميني'],
            ['code' => 'AW', 'country_enName' => 'Aruba', 'country_arName' => 'أروبه', 'country_enNationality' => 'Aruban', 'country_arNationality' => 'أوروبهيني'],
            ['code' => 'AU', 'country_enName' => 'Australia', 'country_arName' => 'أستراليا', 'country_enNationality' => 'Australian', 'country_arNationality' => 'أسترالي'],
            ['code' => 'AT', 'country_enName' => 'Austria', 'country_arName' => 'النمسا', 'country_enNationality' => 'Austrian', 'country_arNationality' => 'نمساوي'],
            ['code' => 'AZ', 'country_enName' => 'Azerbaijan', 'country_arName' => 'أذربيجان', 'country_enNationality' => 'Azerbaijani', 'country_arNationality' => 'أذربيجاني'],
            ['code' => 'BS', 'country_enName' => 'Bahamas', 'country_arName' => 'الباهاماس', 'country_enNationality' => 'Bahamian', 'country_arNationality' => 'باهاميسي'],
            ['code' => 'BH', 'country_enName' => 'Bahrain', 'country_arName' => 'البحرين', 'country_enNationality' => 'Bahraini', 'country_arNationality' => 'بحريني'],
            ['code' => 'BD', 'country_enName' => 'Bangladesh', 'country_arName' => 'بنغلاديش', 'country_enNationality' => 'Bangladeshi', 'country_arNationality' => 'بنغلاديشي'],
            ['code' => 'BB', 'country_enName' => 'Barbados', 'country_arName' => 'بربادوس', 'country_enNationality' => 'Barbadian', 'country_arNationality' => 'بربادوسي'],
            ['code' => 'BY', 'country_enName' => 'Belarus', 'country_arName' => 'روسيا البيضاء', 'country_enNationality' => 'Belarusian', 'country_arNationality' => 'روسي'],
            ['code' => 'BE', 'country_enName' => 'Belgium', 'country_arName' => 'بلجيكا', 'country_enNationality' => 'Belgian', 'country_arNationality' => 'بلجيكي'],
            ['code' => 'BZ', 'country_enName' => 'Belize', 'country_arName' => 'بيليز', 'country_enNationality' => 'Belizean', 'country_arNationality' => 'بيليزي'],
            ['code' => 'BJ', 'country_enName' => 'Benin', 'country_arName' => 'بنين', 'country_enNationality' => 'Beninese', 'country_arNationality' => 'بنيني'],
            ['code' => 'BL', 'country_enName' => 'Saint Barthelemy', 'country_arName' => 'سان بارتيلمي', 'country_enNationality' => 'Saint Barthelmian', 'country_arNationality' => 'سان بارتيلمي'],
            ['code' => 'BM', 'country_enName' => 'Bermuda', 'country_arName' => 'جزر برمودا', 'country_enNationality' => 'Bermudan', 'country_arNationality' => 'برمودي'],
            ['code' => 'BT', 'country_enName' => 'Bhutan', 'country_arName' => 'بوتان', 'country_enNationality' => 'Bhutanese', 'country_arNationality' => 'بوتاني'],
            ['code' => 'BO', 'country_enName' => 'Bolivia', 'country_arName' => 'بوليفيا', 'country_enNationality' => 'Bolivian', 'country_arNationality' => 'بوليفي'],
            ['code' => 'BA', 'country_enName' => 'Bosnia and Herzegovina', 'country_arName' => 'البوسنة و الهرسك', 'country_enNationality' => 'Bosnian / Herzegovinian', 'country_arNationality' => 'بوسني/هرسكي'],
            ['code' => 'BW', 'country_enName' => 'Botswana', 'country_arName' => 'بوتسوانا', 'country_enNationality' => 'Botswanan', 'country_arNationality' => 'بوتسواني'],
            ['code' => 'BV', 'country_enName' => 'Bouvet Island', 'country_arName' => 'جزيرة بوفيه', 'country_enNationality' => 'Bouvetian', 'country_arNationality' => 'بوفيهي'],
            ['code' => 'BR', 'country_enName' => 'Brazil', 'country_arName' => 'البرازيل', 'country_enNationality' => 'Brazilian', 'country_arNationality' => 'برازيلي'],
            ['code' => 'IO', 'country_enName' => 'British Indian Ocean Territory', 'country_arName' => 'إقليم المحيط الهندي البريطاني', 'country_enNationality' => 'British Indian Ocean Territory', 'country_arNationality' => 'إقليم المحيط الهندي البريطاني'],
            ['code' => 'BN', 'country_enName' => 'Brunei Darussalam', 'country_arName' => 'بروني', 'country_enNationality' => 'Bruneian', 'country_arNationality' => 'بروني'],
            ['code' => 'BG', 'country_enName' => 'Bulgaria', 'country_arName' => 'بلغاريا', 'country_enNationality' => 'Bulgarian', 'country_arNationality' => 'بلغاري'],
            ['code' => 'BF', 'country_enName' => 'Burkina Faso', 'country_arName' => 'بوركينا فاسو', 'country_enNationality' => 'Burkinabe', 'country_arNationality' => 'بوركيني'],
            ['code' => 'BI', 'country_enName' => 'Burundi', 'country_arName' => 'بوروندي', 'country_enNationality' => 'Burundian', 'country_arNationality' => 'بورونيدي'],
            ['code' => 'KH', 'country_enName' => 'Cambodia', 'country_arName' => 'كمبوديا', 'country_enNationality' => 'Cambodian', 'country_arNationality' => 'كمبودي'],
            ['code' => 'CM', 'country_enName' => 'Cameroon', 'country_arName' => 'كاميرون', 'country_enNationality' => 'Cameroonian', 'country_arNationality' => 'كاميروني'],
            ['code' => 'CA', 'country_enName' => 'Canada', 'country_arName' => 'كندا', 'country_enNationality' => 'Canadian', 'country_arNationality' => 'كندي'],
            ['code' => 'CV', 'country_enName' => 'Cape Verde', 'country_arName' => 'الرأس الأخضر', 'country_enNationality' => 'Cape Verdean', 'country_arNationality' => 'الرأس الأخضر'],
            ['code' => 'KY', 'country_enName' => 'Cayman Islands', 'country_arName' => 'جزر كايمان', 'country_enNationality' => 'Caymanian', 'country_arNationality' => 'كايماني'],
            ['code' => 'CF', 'country_enName' => 'Central African Republic', 'country_arName' => 'جمهورية أفريقيا الوسطى', 'country_enNationality' => 'Central African', 'country_arNationality' => 'أفريقي'],
            ['code' => 'TD', 'country_enName' => 'Chad', 'country_arName' => 'تشاد', 'country_enNationality' => 'Chadian', 'country_arNationality' => 'تشادي'],
            ['code' => 'CL', 'country_enName' => 'Chile', 'country_arName' => 'شيلي', 'country_enNationality' => 'Chilean', 'country_arNationality' => 'شيلي'],
            ['code' => 'CN', 'country_enName' => 'China', 'country_arName' => 'الصين', 'country_enNationality' => 'Chinese', 'country_arNationality' => 'صيني'],
            ['code' => 'CX', 'country_enName' => 'Christmas Island', 'country_arName' => 'جزيرة عيد الميلاد', 'country_enNationality' => 'Christmas Islander', 'country_arNationality' => 'جزيرة عيد الميلاد'],
            ['code' => 'CC', 'country_enName' => 'Cocos (Keeling) Islands', 'country_arName' => 'جزر كوكوس', 'country_enNationality' => 'Cocos Islander', 'country_arNationality' => 'جزر كوكوس'],
            ['code' => 'CO', 'country_enName' => 'Colombia', 'country_arName' => 'كولومبيا', 'country_enNationality' => 'Colombian', 'country_arNationality' => 'كولومبي'],
            ['code' => 'KM', 'country_enName' => 'Comoros', 'country_arName' => 'جزر القمر', 'country_enNationality' => 'Comorian', 'country_arNationality' => 'جزر القمر'],
            ['code' => 'CG', 'country_enName' => 'Congo', 'country_arName' => 'الكونغو', 'country_enNationality' => 'Congolese', 'country_arNationality' => 'كونغي'],
            ['code' => 'CK', 'country_enName' => 'Cook Islands', 'country_arName' => 'جزر كوك', 'country_enNationality' => 'Cook Islander', 'country_arNationality' => 'جزر كوك'],
            ['code' => 'CR', 'country_enName' => 'Costa Rica', 'country_arName' => 'كوستاريكا', 'country_enNationality' => 'Costa Rican', 'country_arNationality' => 'كوستاريكي'],
            ['code' => 'HR', 'country_enName' => 'Croatia', 'country_arName' => 'كرواتيا', 'country_enNationality' => 'Croatian', 'country_arNationality' => 'كوراتي'],
            ['code' => 'CU', 'country_enName' => 'Cuba', 'country_arName' => 'كوبا', 'country_enNationality' => 'Cuban', 'country_arNationality' => 'كوبي'],
            ['code' => 'CY', 'country_enName' => 'Cyprus', 'country_arName' => 'قبرص', 'country_enNationality' => 'Cypriot', 'country_arNationality' => 'قبرصي'],
            ['code' => 'CW', 'country_enName' => 'Curaçao', 'country_arName' => 'كوراساو', 'country_enNationality' => 'Curacian', 'country_arNationality' => 'كوراساوي'],
            ['code' => 'CZ', 'country_enName' => 'Czech Republic', 'country_arName' => 'الجمهورية التشيكية', 'country_enNationality' => 'Czech', 'country_arNationality' => 'تشيكي'],
            ['code' => 'DK', 'country_enName' => 'Denmark', 'country_arName' => 'الدانمارك', 'country_enNationality' => 'Danish', 'country_arNationality' => 'دنماركي'],
            ['code' => 'DJ', 'country_enName' => 'Djibouti', 'country_arName' => 'جيبوتي', 'country_enNationality' => 'Djiboutian', 'country_arNationality' => 'جيبوتي'],
            ['code' => 'DM', 'country_enName' => 'Dominica', 'country_arName' => 'دومينيكا', 'country_enNationality' => 'Dominican', 'country_arNationality' => 'دومينيكي'],
            ['code' => 'DO', 'country_enName' => 'Dominican Republic', 'country_arName' => 'الجمهورية الدومينيكية', 'country_enNationality' => 'Dominican', 'country_arNationality' => 'دومينيكي'],
            ['code' => 'EC', 'country_enName' => 'Ecuador', 'country_arName' => 'إكوادور', 'country_enNationality' => 'Ecuadorian', 'country_arNationality' => 'إكوادوري'],
            ['code' => 'EG', 'country_enName' => 'Egypt', 'country_arName' => 'مصر', 'country_enNationality' => 'Egyptian', 'country_arNationality' => 'مصري'],
            ['code' => 'SV', 'country_enName' => 'El Salvador', 'country_arName' => 'إلسلفادور', 'country_enNationality' => 'Salvadoran', 'country_arNationality' => 'سلفادوري'],
            ['code' => 'GQ', 'country_enName' => 'Equatorial Guinea', 'country_arName' => 'غينيا الاستوائي', 'country_enNationality' => 'Equatorial Guinean', 'country_arNationality' => 'غيني'],
            ['code' => 'ER', 'country_enName' => 'Eritrea', 'country_arName' => 'إريتريا', 'country_enNationality' => 'Eritrean', 'country_arNationality' => 'إريتيري'],
            ['code' => 'EE', 'country_enName' => 'Estonia', 'country_arName' => 'استونيا', 'country_enNationality' => 'Estonian', 'country_arNationality' => 'استوني'],
            ['code' => 'ET', 'country_enName' => 'Ethiopia', 'country_arName' => 'أثيوبيا', 'country_enNationality' => 'Ethiopian', 'country_arNationality' => 'أثيوبي'],
            ['code' => 'FK', 'country_enName' => 'Falkland Islands (Malvinas)', 'country_arName' => 'جزر فوكلاند', 'country_enNationality' => 'Falkland Islander', 'country_arNationality' => 'فوكلاندي'],
            ['code' => 'FO', 'country_enName' => 'Faroe Islands', 'country_arName' => 'جزر فارو', 'country_enNationality' => 'Faroese', 'country_arNationality' => 'جزر فارو'],
            ['code' => 'FJ', 'country_enName' => 'Fiji', 'country_arName' => 'فيجي', 'country_enNationality' => 'Fijian', 'country_arNationality' => 'فيجي'],
            ['code' => 'FI', 'country_enName' => 'Finland', 'country_arName' => 'فنلندا', 'country_enNationality' => 'Finnish', 'country_arNationality' => 'فنلندي'],
            ['code' => 'FR', 'country_enName' => 'France', 'country_arName' => 'فرنسا', 'country_enNationality' => 'French', 'country_arNationality' => 'فرنسي'],
            ['code' => 'GF', 'country_enName' => 'French Guiana', 'country_arName' => 'غويانا الفرنسية', 'country_enNationality' => 'French Guianese', 'country_arNationality' => 'غويانا الفرنسية'],
            ['code' => 'PF', 'country_enName' => 'French Polynesia', 'country_arName' => 'بولينيزيا الفرنسية', 'country_enNationality' => 'French Polynesian', 'country_arNationality' => 'بولينيزيي'],
            ['code' => 'TF', 'country_enName' => 'French Southern and Antarctic Lands', 'country_arName' => 'أراض فرنسية جنوبية وأنتارتيكية', 'country_enNationality' => 'French', 'country_arNationality' => 'أراض فرنسية جنوبية وأنتارتيكية'],
            ['code' => 'GA', 'country_enName' => 'Gabon', 'country_arName' => 'الغابون', 'country_enNationality' => 'Gabonese', 'country_arNationality' => 'غابوني'],
            ['code' => 'GM', 'country_enName' => 'Gambia', 'country_arName' => 'غامبيا', 'country_enNationality' => 'Gambian', 'country_arNationality' => 'غامبي'],
            ['code' => 'GE', 'country_enName' => 'Georgia', 'country_arName' => 'جيورجيا', 'country_enNationality' => 'Georgian', 'country_arNationality' => 'جيورجي'],
            ['code' => 'DE', 'country_enName' => 'Germany', 'country_arName' => 'ألمانيا', 'country_enNationality' => 'German', 'country_arNationality' => 'ألماني'],
            ['code' => 'GH', 'country_enName' => 'Ghana', 'country_arName' => 'غانا', 'country_enNationality' => 'Ghanaian', 'country_arNationality' => 'غاني'],
            ['code' => 'GI', 'country_enName' => 'Gibraltar', 'country_arName' => 'جبل طارق', 'country_enNationality' => 'Gibraltar', 'country_arNationality' => 'جبل طارق'],
            ['code' => 'GG', 'country_enName' => 'Guernsey', 'country_arName' => 'غيرنزي', 'country_enNationality' => 'Guernsian', 'country_arNationality' => 'غيرنزي'],
            ['code' => 'GR', 'country_enName' => 'Greece', 'country_arName' => 'اليونان', 'country_enNationality' => 'Greek', 'country_arNationality' => 'يوناني'],
            ['code' => 'GL', 'country_enName' => 'Greenland', 'country_arName' => 'جرينلاند', 'country_enNationality' => 'Greenlandic', 'country_arNationality' => 'جرينلاندي'],
            ['code' => 'GD', 'country_enName' => 'Grenada', 'country_arName' => 'غرينادا', 'country_enNationality' => 'Grenadian', 'country_arNationality' => 'غرينادي'],
            ['code' => 'GP', 'country_enName' => 'Guadeloupe', 'country_arName' => 'جزر جوادلوب', 'country_enNationality' => 'Guadeloupe', 'country_arNationality' => 'جزر جوادلوب'],
            ['code' => 'GU', 'country_enName' => 'Guam', 'country_arName' => 'جوام', 'country_enNationality' => 'Guamanian', 'country_arNationality' => 'جوامي'],            ['code' => 'Afghanistan', 'country_enName' => 'AF', 'country_arName' => 'AF', 'country_enNationality' => 'AF', 'country_arNationality' => 'AF'],
            ['code' => 'GT', 'country_enName' => 'Guatemala', 'country_arName' => 'غواتيمال', 'country_enNationality' => 'Guatemalan', 'country_arNationality' => 'غواتيمالي'],
            ['code' => 'GN', 'country_enName' => 'Guinea', 'country_arName' => 'غينيا', 'country_enNationality' => 'Guinean', 'country_arNationality' => 'غيني'],
            ['code' => 'GW', 'country_enName' => 'Guinea-Bissau', 'country_arName' => 'غينيا-بيساو', 'country_enNationality' => 'Guinea-Bissauan', 'country_arNationality' => 'غيني'],
            ['code' => 'GY', 'country_enName' => 'Guyana', 'country_arName' => 'غيانا', 'country_enNationality' => 'Guyanese', 'country_arNationality' => 'غياني'],
            ['code' => 'HT', 'country_enName' => 'Haiti', 'country_arName' => 'هايتي', 'country_enNationality' => 'Haitian', 'country_arNationality' => 'هايتي'],
            ['code' => 'HM', 'country_enName' => 'Heard and Mc Donald Islands', 'country_arName' => 'جزيرة هيرد وجزر ماكدونالد', 'country_enNationality' => 'Heard and Mc Donald Islanders', 'country_arNationality' => 'جزيرة هيرد وجزر ماكدونالد'],
            ['code' => 'HN', 'country_enName' => 'Honduras', 'country_arName' => 'هندوراس', 'country_enNationality' => 'Honduran', 'country_arNationality' => 'هندوراسي'],
            ['code' => 'HK', 'country_enName' => 'Hong Kong', 'country_arName' => 'هونغ كونغ', 'country_enNationality' => 'Hongkongese', 'country_arNationality' => 'هونغ كونغي'],
            ['code' => 'HU', 'country_enName' => 'Hungary', 'country_arName' => 'المجر', 'country_enNationality' => 'Hungarian', 'country_arNationality' => 'مجري'],
            ['code' => 'IS', 'country_enName' => 'Iceland', 'country_arName' => 'آيسلندا', 'country_enNationality' => 'Icelandic', 'country_arNationality' => 'آيسلندي'],
            ['code' => 'IN', 'country_enName' => 'India', 'country_arName' => 'الهند', 'country_enNationality' => 'Indian', 'country_arNationality' => 'هندي'],
            ['code' => 'IM', 'country_enName' => 'Isle of Man', 'country_arName' => 'جزيرة مان', 'country_enNationality' => 'Manx', 'country_arNationality' => 'ماني'],
            ['code' => 'ID', 'country_enName' => 'Indonesia', 'country_arName' => 'أندونيسيا', 'country_enNationality' => 'Indonesian', 'country_arNationality' => 'أندونيسيي'],
            ['code' => 'IR', 'country_enName' => 'Iran', 'country_arName' => 'إيران', 'country_enNationality' => 'Iranian', 'country_arNationality' => 'إيراني'],
            ['code' => 'IQ', 'country_enName' => 'Iraq', 'country_arName' => 'العراق', 'country_enNationality' => 'Iraqi', 'country_arNationality' => 'Iraqi'],
            ['code' => 'IE', 'country_enName' => 'Ireland', 'country_arName' => 'إيرلندا', 'country_enNationality' => 'Irish', 'country_arNationality' => 'إيرلندي'],
            ['code' => 'IT', 'country_enName' => 'Italy', 'country_arName' => 'إيطاليا', 'country_enNationality' => 'Italian', 'country_arNationality' => 'إيطالي'],
            ['code' => 'CI', 'country_enName' => 'Ivory Coast', 'country_arName' => 'ساحل العاج', 'country_enNationality' => 'Ivory Coastian', 'country_arNationality' => 'ساحل العاج'],
            ['code' => 'JE', 'country_enName' => 'Jersey', 'country_arName' => 'جيرزي', 'country_enNationality' => 'Jersian', 'country_arNationality' => 'جيرزي'],
            ['code' => 'JM', 'country_enName' => 'Jamaica', 'country_arName' => 'جمايكا', 'country_enNationality' => 'Jamaican', 'country_arNationality' => 'جمايكي'],
            ['code' => 'JP', 'country_enName' => 'Japan', 'country_arName' => 'اليابان', 'country_enNationality' => 'Japanese', 'country_arNationality' => 'ياباني'],
            ['code' => 'JO', 'country_enName' => 'Jordan', 'country_arName' => 'الأردن', 'country_enNationality' => 'Jordanian', 'country_arNationality' => 'أردني'],
            ['code' => 'KZ', 'country_enName' => 'Kazakhstan', 'country_arName' => 'كازاخستان', 'country_enNationality' => 'Kazakh', 'country_arNationality' => 'كازاخستاني'],
            ['code' => 'KE', 'country_enName' => 'Kenya', 'country_arName' => 'كينيا', 'country_enNationality' => 'Kenyan', 'country_arNationality' => 'كيني'],
            ['code' => 'KI', 'country_enName' => 'Kiribati', 'country_arName' => 'كيريباتي', 'country_enNationality' => 'I-Kiribati', 'country_arNationality' => 'كيريباتي'],
            ['code' => 'KP', 'country_enName' => 'Korea(North Korea)', 'country_arName' => 'كوريا الشمالية', 'country_enNationality' => 'North Korean', 'country_arNationality' => 'كوري'],
            ['code' => 'KR', 'country_enName' => 'Korea(South Korea)', 'country_arName' => 'كوريا الجنوبية', 'country_enNationality' => 'South Korean', 'country_arNationality' => 'كوري'],
            ['code' => 'XK', 'country_enName' => 'Kosovo', 'country_arName' => 'كوسوفو', 'country_enNationality' => 'Kosovar', 'country_arNationality' => 'كوسيفي'],
            ['code' => 'KW', 'country_enName' => 'Kuwait', 'country_arName' => 'الكويت', 'country_enNationality' => 'Kuwaiti', 'country_arNationality' => 'كويتي'],
            ['code' => 'KG', 'country_enName' => 'Kyrgyzstan', 'country_arName' => 'قيرغيزستان', 'country_enNationality' => 'Kyrgyzstani', 'country_arNationality' => 'قيرغيزستاني'],
            ['code' => 'LA', 'country_enName' => 'Lao PDR', 'country_arName' => 'لاوس', 'country_enNationality' => 'Laotian', 'country_arNationality' => 'لاوسي'],
            ['code' => 'LV', 'country_enName' => 'Latvia', 'country_arName' => 'لاتفيا', 'country_enNationality' => 'Latvian', 'country_arNationality' => 'لاتيفي'],
            ['code' => 'LB', 'country_enName' => 'Lebanon', 'country_arName' => 'لبنان', 'country_enNationality' => 'Lebanese', 'country_arNationality' => 'لبناني'],
            ['code' => 'LS', 'country_enName' => 'Lesotho', 'country_arName' => 'ليسوتو', 'country_enNationality' => 'Basotho', 'country_arNationality' => 'ليوسيتي'],
            ['code' => 'LR', 'country_enName' => 'Liberia', 'country_arName' => 'ليبيريا', 'country_enNationality' => 'Liberian', 'country_arNationality' => 'ليبيري'],
            ['code' => 'LY', 'country_enName' => 'Libya', 'country_arName' => 'ليبيا', 'country_enNationality' => 'Libyan', 'country_arNationality' => 'ليبي'],
            ['code' => 'LI', 'country_enName' => 'Liechtenstein', 'country_arName' => 'ليختنشتين', 'country_enNationality' => 'Liechtenstein', 'country_arNationality' => 'ليختنشتيني'],
            ['code' => 'LT', 'country_enName' => 'Lithuania', 'country_arName' => 'لتوانيا', 'country_enNationality' => 'Lithuanian', 'country_arNationality' => 'لتوانيي'],
            ['code' => 'LU', 'country_enName' => 'Luxembourg', 'country_arName' => 'لوكسمبورغ', 'country_enNationality' => 'Luxembourger', 'country_arNationality' => 'لوكسمبورغي'],
            ['code' => 'LK', 'country_enName' => 'Sri Lanka', 'country_arName' => 'سريلانكا', 'country_enNationality' => 'Sri Lankian', 'country_arNationality' => 'سريلانكي'],
            ['code' => 'MO', 'country_enName' => 'Macau', 'country_arName' => 'ماكاو', 'country_enNationality' => 'Macanese', 'country_arNationality' => 'ماكاوي'],
            ['code' => 'MK', 'country_enName' => 'Macedonia', 'country_arName' => 'مقدونيا', 'country_enNationality' => 'Macedonian', 'country_arNationality' => 'مقدوني'],
            ['code' => 'MG', 'country_enName' => 'Madagascar', 'country_arName' => 'مدغشقر', 'country_enNationality' => 'Malagasy', 'country_arNationality' => 'مدغشقري'],
            ['code' => 'MW', 'country_enName' => 'Malawi', 'country_arName' => 'مالاوي', 'country_enNationality' => 'Malawian', 'country_arNationality' => 'مالاوي'],
            ['code' => 'MY', 'country_enName' => 'Malaysia', 'country_arName' => 'ماليزيا', 'country_enNationality' => 'Malaysian', 'country_arNationality' => 'ماليزي'],
            ['code' => 'MV', 'country_enName' => 'Maldives', 'country_arName' => 'المالديف', 'country_enNationality' => 'Maldivian', 'country_arNationality' => 'مالديفي'],
            ['code' => 'ML', 'country_enName' => 'Mali', 'country_arName' => 'مالي', 'country_enNationality' => 'Malian', 'country_arNationality' => 'مالي'],
            ['code' => 'MT', 'country_enName' => 'Malta', 'country_arName' => 'مالطا', 'country_enNationality' => 'Maltese', 'country_arNationality' => 'مالطي'],
            ['code' => 'MH', 'country_enName' => 'Marshall Islands', 'country_arName' => 'جزر مارشال', 'country_enNationality' => 'Marshallese', 'country_arNationality' => 'مارشالي'],
            ['code' => 'MQ', 'country_enName' => 'Martinique', 'country_arName' => 'مارتينيك', 'country_enNationality' => 'Martiniquais', 'country_arNationality' => 'مارتينيكي'],
            ['code' => 'MR', 'country_enName' => 'Mauritania', 'country_arName' => 'موريتانيا', 'country_enNationality' => 'Mauritanian', 'country_arNationality' => 'موريتانيي'],
            ['code' => 'MU', 'country_enName' => 'Mauritius', 'country_arName' => 'موريشيوس', 'country_enNationality' => 'Mauritian', 'country_arNationality' => 'موريشيوسي'],
            ['code' => 'YT', 'country_enName' => 'Mayotte', 'country_arName' => 'مايوت', 'country_enNationality' => 'Mahoran', 'country_arNationality' => 'مايوتي'],
            ['code' => 'MX', 'country_enName' => 'Mexico', 'country_arName' => 'المكسيك', 'country_enNationality' => 'Mexican', 'country_arNationality' => 'مكسيكي'],
            ['code' => 'FM', 'country_enName' => 'Micronesia', 'country_arName' => 'مايكرونيزيا', 'country_enNationality' => 'Micronesian', 'country_arNationality' => 'مايكرونيزيي'],
            ['code' => 'MD', 'country_enName' => 'Moldova', 'country_arName' => 'مولدافيا', 'country_enNationality' => 'Moldovan', 'country_arNationality' => 'مولديفي'],
            ['code' => 'MC', 'country_enName' => 'Monaco', 'country_arName' => 'موناكو', 'country_enNationality' => 'Monacan', 'country_arNationality' => 'مونيكي'],
            ['code' => 'MN', 'country_enName' => 'Mongolia', 'country_arName' => 'منغوليا', 'country_enNationality' => 'Mongolian', 'country_arNationality' => 'منغولي'],
            ['code' => 'ME', 'country_enName' => 'Montenegro', 'country_arName' => 'الجبل الأسود', 'country_enNationality' => 'Montenegrin', 'country_arNationality' => 'الجبل الأسود'],
            ['code' => 'MS', 'country_enName' => 'Montserrat', 'country_arName' => 'مونتسيرات', 'country_enNationality' => 'Montserratian', 'country_arNationality' => 'مونتسيراتي'],
            ['code' => 'MA', 'country_enName' => 'Morocco', 'country_arName' => 'المغرب', 'country_enNationality' => 'Moroccan', 'country_arNationality' => 'مغربي'],
            ['code' => 'MZ', 'country_enName' => 'Mozambique', 'country_arName' => 'موزمبيق', 'country_enNationality' => 'Mozambican', 'country_arNationality' => 'موزمبيقي'],
            ['code' => 'MM', 'country_enName' => 'Myanmar', 'country_arName' => 'ميانمار', 'country_enNationality' => 'Myanmarian', 'country_arNationality' => 'ميانماري'],
            ['code' => 'NA', 'country_enName' => 'Namibia', 'country_arName' => 'ناميبيا', 'country_enNationality' => 'Namibian', 'country_arNationality' => 'ناميبي'],
            ['code' => 'NR', 'country_enName' => 'Nauru', 'country_arName' => 'نورو', 'country_enNationality' => 'Nauruan', 'country_arNationality' => 'نوري'],            ['code' => 'Afghanistan', 'country_enName' => 'AF', 'country_arName' => 'AF', 'country_enNationality' => 'AF', 'country_arNationality' => 'AF'],
            ['code' => 'NP', 'country_enName' => 'Nepal', 'country_arName' => 'نيبال', 'country_enNationality' => 'Nepalese', 'country_arNationality' => 'نيبالي'],
            ['code' => 'NL', 'country_enName' => 'Netherlands', 'country_arName' => 'هولندا', 'country_enNationality' => 'Dutch', 'country_arNationality' => 'هولندي'],
            ['code' => 'AN', 'country_enName' => 'Netherlands Antilles', 'country_arName' => 'جزر الأنتيل الهولندي', 'country_enNationality' => 'Dutch Antilier', 'country_arNationality' => 'هولندي'],
            ['code' => 'NC', 'country_enName' => 'New Caledonia', 'country_arName' => 'كاليدونيا الجديدة', 'country_enNationality' => 'New Caledonian', 'country_arNationality' => 'كاليدوني'],
            ['code' => 'NZ', 'country_enName' => 'New Zealand', 'country_arName' => 'نيوزيلندا', 'country_enNationality' => 'New Zealander', 'country_arNationality' => 'نيوزيلندي'],
            ['code' => 'NI', 'country_enName' => 'Nicaragua', 'country_arName' => 'نيكاراجوا', 'country_enNationality' => 'Nicaraguan', 'country_arNationality' => 'نيكاراجوي'],
            ['code' => 'NE', 'country_enName' => 'Niger', 'country_arName' => 'النيجر', 'country_enNationality' => 'Nigerien', 'country_arNationality' => 'نيجيري'],
            ['code' => 'NG', 'country_enName' => 'Nigeria', 'country_arName' => 'نيجيريا', 'country_enNationality' => 'Nigerian', 'country_arNationality' => 'نيجيري'],
            ['code' => 'NU', 'country_enName' => 'Niue', 'country_arName' => 'ني', 'country_enNationality' => 'Niuean', 'country_arNationality' => 'ني'],
            ['code' => 'NF', 'country_enName' => 'Norfolk Island', 'country_arName' => 'جزيرة نورفولك', 'country_enNationality' => 'Norfolk Islander', 'country_arNationality' => 'نورفوليكي'],
            ['code' => 'MP', 'country_enName' => 'Northern Mariana Islands', 'country_arName' => 'جزر ماريانا الشمالية', 'country_enNationality' => 'Northern Marianan', 'country_arNationality' => 'ماريني'],
            ['code' => 'NO', 'country_enName' => 'Norway', 'country_arName' => 'النرويج', 'country_enNationality' => 'Norwegian', 'country_arNationality' => 'نرويجي'],
            ['code' => 'OM', 'country_enName' => 'Oman', 'country_arName' => 'عمان', 'country_enNationality' => 'Omani', 'country_arNationality' => 'عماني'],
            ['code' => 'PK', 'country_enName' => 'Pakistan', 'country_arName' => 'باكستان', 'country_enNationality' => 'Pakistani', 'country_arNationality' => 'باكستاني'],
            ['code' => 'PW', 'country_enName' => 'Palau', 'country_arName' => 'بالاو', 'country_enNationality' => 'Palauan', 'country_arNationality' => 'بالاوي'],
            ['code' => 'PS', 'country_enName' => 'Palestine', 'country_arName' => 'فلسطين', 'country_enNationality' => 'Palestinian', 'country_arNationality' => 'فلسطيني'],
            ['code' => 'PA', 'country_enName' => 'Panama', 'country_arName' => 'Panama', 'country_enNationality' => 'Panamanian', 'country_arNationality' => 'بنمي'],
            ['code' => 'PG', 'country_enName' => 'Papua New Guinea', 'country_arName' => 'بابوا غينيا الجديدة', 'country_enNationality' => 'Papua New Guinean', 'country_arNationality' => 'بابوي'],
            ['code' => 'PY', 'country_enName' => 'Paraguay', 'country_arName' => 'باراغواي', 'country_enNationality' => 'Paraguayan', 'country_arNationality' => 'بارغاوي'],
            ['code' => 'PE', 'country_enName' => 'Peru', 'country_arName' => 'بيرو', 'country_enNationality' => 'Peruvian', 'country_arNationality' => 'بيري'],
            ['code' => 'PH', 'country_enName' => 'Philippines', 'country_arName' => 'الفليبين', 'country_enNationality' => 'Filipino', 'country_arNationality' => 'فلبيني'],
            ['code' => 'PN', 'country_enName' => 'Pitcairn', 'country_arName' => 'بيتكيرن', 'country_enNationality' => 'Pitcairn Islander', 'country_arNationality' => 'بيتكيرني'],
            ['code' => 'PL', 'country_enName' => 'Poland', 'country_arName' => 'بولونيا', 'country_enNationality' => 'Polish', 'country_arNationality' => 'بوليني'],
            ['code' => 'PT', 'country_enName' => 'Portugal', 'country_arName' => 'البرتغال', 'country_enNationality' => 'Portuguese', 'country_arNationality' => 'برتغالي'],
            ['code' => 'PR', 'country_enName' => 'Puerto Rico', 'country_arName' => 'بورتو ريكو', 'country_enNationality' => 'Puerto Rican', 'country_arNationality' => 'بورتي'],
            ['code' => 'QA', 'country_enName' => 'Qatar', 'country_arName' => 'قطر', 'country_enNationality' => 'Qatari', 'country_arNationality' => 'قطري'],
            ['code' => 'RE', 'country_enName' => 'Reunion Island', 'country_arName' => 'ريونيون', 'country_enNationality' => 'Reunionese', 'country_arNationality' => 'ريونيوني'],
            ['code' => 'RO', 'country_enName' => 'Romania', 'country_arName' => 'رومانيا', 'country_enNationality' => 'Romanian', 'country_arNationality' => 'روماني'],
            ['code' => 'RU', 'country_enName' => 'Russian', 'country_arName' => 'روسيا', 'country_enNationality' => 'Russian', 'country_arNationality' => 'روسي'],
            ['code' => 'RW', 'country_enName' => 'Rwanda', 'country_arName' => 'رواندا', 'country_enNationality' => 'Rwandan', 'country_arNationality' => 'رواندا'],
            ['code' => 'KN', 'country_enName' => 'Saint Kitts and Nevis', 'country_arName' => 'سانت كيتس ونيفس', 'country_enNationality' => 'Kittitian/Nevisian', 'country_arNationality' => 'سانت كيتس ونيفس'],
            ['code' => 'MF', 'country_enName' => 'Saint Martin (French part)', 'country_arName' => 'ساينت مارتن فرنسي', 'country_enNationality' => 'St. Martian(French)', 'country_arNationality' => 'ساينت مارتني فرنسي'],
            ['code' => 'SX', 'country_enName' => 'Sint Maarten (Dutch part)', 'country_arName' => 'ساينت مارتن هولندي', 'country_enNationality' => 'St. Martian(Dutch)', 'country_arNationality' => 'ساينت مارتني هولندي'],
            ['code' => 'LC', 'country_enName' => 'Saint Pierre and Miquelon', 'country_arName' => 'سان بيير وميكلون', 'country_enNationality' => 'St. Pierre and Miquelon', 'country_arNationality' => 'سان بيير وميكلوني'],
            ['code' => 'VC', 'country_enName' => 'Saint Vincent and the Grenadines', 'country_arName' => 'سانت فنسنت وجزر غرينادين', 'country_enNationality' => 'Saint Vincent and the Grenadines', 'country_arNationality' => 'سانت فنسنت وجزر غرينادين'],
            ['code' => 'WS', 'country_enName' => 'Samoa', 'country_arName' => 'ساموا', 'country_enNationality' => 'Samoan', 'country_arNationality' => 'ساموي'],
            ['code' => 'SM', 'country_enName' => 'San Marino', 'country_arName' => 'سان مارينو', 'country_enNationality' => 'Sammarinese', 'country_arNationality' => 'ماريني'],
            ['code' => 'ST', 'country_enName' => 'Sao Tome and Principe', 'country_arName' => 'ساو تومي وبرينسيبي', 'country_enNationality' => 'Sao Tomean', 'country_arNationality' => 'ساو تومي وبرينسيبي'],
            ['code' => 'SA', 'country_enName' => 'Saudi Arabia', 'country_arName' => 'المملكة العربية السعودية', 'country_enNationality' => 'Saudi Arabian', 'country_arNationality' => 'سعودي'],
            ['code' => 'SN', 'country_enName' => 'Senegal', 'country_arName' => 'السنغال', 'country_enNationality' => 'Senegalese', 'country_arNationality' => 'سنغالي'],
            ['code' => 'RS', 'country_enName' => 'Serbia', 'country_arName' => 'صربيا', 'country_enNationality' => 'Serbian', 'country_arNationality' => 'صربي'],
            ['code' => 'SC', 'country_enName' => 'Seychelles', 'country_arName' => 'سيشيل', 'country_enNationality' => 'Seychellois', 'country_arNationality' => 'سيشيلي'],
            ['code' => 'SL', 'country_enName' => 'Sierra Leone', 'country_arName' => 'سيراليون', 'country_enNationality' => 'Sierra Leonean', 'country_arNationality' => 'سيراليوني'],
            ['code' => 'SG', 'country_enName' => 'Singapore', 'country_arName' => 'سنغافورة', 'country_enNationality' => 'Singaporean', 'country_arNationality' => 'سنغافوري'],
            ['code' => 'SK', 'country_enName' => 'Slovakia', 'country_arName' => 'سلوفاكيا', 'country_enNationality' => 'Slovak', 'country_arNationality' => 'سولفاكي'],
            ['code' => 'SI', 'country_enName' => 'Slovenia', 'country_arName' => 'سلوفينيا', 'country_enNationality' => 'Slovenian', 'country_arNationality' => 'سولفيني'],
            ['code' => 'SB', 'country_enName' => 'Solomon Islands', 'country_arName' => 'جزر سليمان', 'country_enNationality' => 'Solomon Island', 'country_arNationality' => 'جزر سليمان'],
            ['code' => 'SO', 'country_enName' => 'Somalia', 'country_arName' => 'الصومال', 'country_enNationality' => 'Somali', 'country_arNationality' => 'صومالي'],
            ['code' => 'ZA', 'country_enName' => 'South Africa', 'country_arName' => 'جنوب أفريقيا', 'country_enNationality' => 'South African', 'country_arNationality' => 'أفريقي'],
            ['code' => 'SS', 'country_enName' => 'South Sudan', 'country_arName' => 'السودان الجنوبي', 'country_enNationality' => 'South Sudanese', 'country_arNationality' => 'سوادني جنوبي'],
            ['code' => 'ES', 'country_enName' => 'Spain', 'country_arName' => 'إسبانيا', 'country_enNationality' => 'Spanish', 'country_arNationality' => 'إسباني'],
            ['code' => 'SH', 'country_enName' => 'Saint Helena', 'country_arName' => 'سانت هيلانة', 'country_enNationality' => 'St. Helenian', 'country_arNationality' => 'هيلاني'],
            ['code' => 'SD', 'country_enName' => 'Sudan', 'country_arName' => 'السودان', 'country_enNationality' => 'Sudanese', 'country_arNationality' => 'سوداني'],
            ['code' => 'SR', 'country_enName' => 'Suriname', 'country_arName' => 'سورينام', 'country_enNationality' => 'Surinamese', 'country_arNationality' => 'سورينامي'],
            ['code' => 'SZ', 'country_enName' => 'Swaziland', 'country_arName' => 'سوازيلند', 'country_enNationality' => 'Swazi', 'country_arNationality' => 'سوازيلندي'],
            ['code' => 'SE', 'country_enName' => 'Sweden', 'country_arName' => 'السويد', 'country_enNationality' => 'Swedish', 'country_arNationality' => 'سويدي'],
            ['code' => 'CH', 'country_enName' => 'Switzerland', 'country_arName' => 'سويسرا', 'country_enNationality' => 'Swiss', 'country_arNationality' => 'سويسري'],
            ['code' => 'SY', 'country_enName' => 'Syria', 'country_arName' => 'سوريا', 'country_enNationality' => 'Syrian', 'country_arNationality' => 'سوري'],
            ['code' => 'TW', 'country_enName' => 'Taiwan', 'country_arName' => 'تايوان', 'country_enNationality' => 'Taiwanese', 'country_arNationality' => 'تايواني'],
            ['code' => 'TJ', 'country_enName' => 'Tajikistan', 'country_arName' => 'طاجيكستان', 'country_enNationality' => 'Tajikistani', 'country_arNationality' => 'طاجيكستاني'],
            ['code' => 'TZ', 'country_enName' => 'Tanzania', 'country_arName' => 'تنزانيا', 'country_enNationality' => 'Tanzanian', 'country_arNationality' => 'تنزانيي'],
            ['code' => 'TH', 'country_enName' => 'Thailand', 'country_arName' => 'تايلندا', 'country_enNationality' => 'Thai', 'country_arNationality' => 'تايلندي'],
            ['code' => 'TL', 'country_enName' => 'Timor-Leste', 'country_arName' => 'تيمور الشرقية', 'country_enNationality' => 'Timor-Lestian', 'country_arNationality' => 'تيموري'],
            ['code' => 'TG', 'country_enName' => 'Togo', 'country_arName' => 'توغو', 'country_enNationality' => 'Togolese', 'country_arNationality' => 'توغي'],
            ['code' => 'TK', 'country_enName' => 'Tokelau', 'country_arName' => 'توكيلاو', 'country_enNationality' => 'Tokelaian', 'country_arNationality' => 'توكيلاوي'],
            ['code' => 'TO', 'country_enName' => 'Tonga', 'country_arName' => 'تونغا', 'country_enNationality' => 'Tongan', 'country_arNationality' => 'تونغي'],
            ['code' => 'TN', 'country_enName' => 'Tunisia', 'country_arName' => 'تونس', 'country_enNationality' => 'Tunisian', 'country_arNationality' => 'تونسي'],
            ['code' => 'TR', 'country_enName' => 'Turkey', 'country_arName' => 'تركيا', 'country_enNationality' => 'Turkish', 'country_arNationality' => 'تركي'],
            ['code' => 'TM', 'country_enName' => 'Turkmenistan', 'country_arName' => 'تركمانستان', 'country_enNationality' => 'Turkmen', 'country_arNationality' => 'تركمانستاني'],
            ['code' => 'TV', 'country_enName' => 'Tuvalu', 'country_arName' => 'توفالو', 'country_enNationality' => 'Tuvaluan', 'country_arNationality' => 'توفالي'],
            ['code' => 'UG', 'country_enName' => 'Uganda', 'country_arName' => 'أوغندا', 'country_enNationality' => 'Ugandan', 'country_arNationality' => 'أوغندي'],
            ['code' => 'UA', 'country_enName' => 'Ukraine', 'country_arName' => 'Ukraine', 'country_enNationality' => 'Ukrainian', 'country_arNationality' => 'أوكراني'],
            ['code' => 'AE', 'country_enName' => 'United Arab Emirates', 'country_arName' => 'الإمارات العربية المتحدة', 'country_enNationality' => 'Emirati', 'country_arNationality' => 'إماراتي'],
            ['code' => 'GB', 'country_enName' => 'United Kingdom', 'country_arName' => 'المملكة المتحدة', 'country_enNationality' => 'British', 'country_arNationality' => 'بريطاني'],
            ['code' => 'US', 'country_enName' => 'United States', 'country_arName' => 'الولايات المتحدة', 'country_enNationality' => 'American', 'country_arNationality' => 'أمريكي'],
            ['code' => 'UY', 'country_enName' => 'Uruguay', 'country_arName' => 'أورغواي', 'country_enNationality' => 'Uruguayan', 'country_arNationality' => 'أورغواي'],
            ['code' => 'UZ', 'country_enName' => 'Uzbekistan', 'country_arName' => 'أوزباكستان', 'country_enNationality' => 'Uzbek', 'country_arNationality' => 'أوزباكستاني'],
            ['code' => 'VU', 'country_enName' => 'Vanuatu', 'country_arName' => 'فانواتو', 'country_enNationality' => 'Vanuatuan', 'country_arNationality' => 'فانواتي'],
            ['code' => 'VE', 'country_enName' => 'Venezuela', 'country_arName' => 'فنزويلا', 'country_enNationality' => 'Venezuelan', 'country_arNationality' => 'فنزويلي'],
            ['code' => 'VN', 'country_enName' => 'Vietnam', 'country_arName' => 'فيتنام', 'country_enNationality' => 'Vietnamese', 'country_arNationality' => 'فيتنامي'],
            ['code' => 'VA', 'country_enName' => 'Vatican City', 'country_arName' => 'فاتيكان', 'country_enNationality' => 'Vatican', 'country_arNationality' => 'فاتيكاني'],
            ['code' => 'EH', 'country_enName' => 'Western Sahara', 'country_arName' => 'الصحراء الغربية', 'country_enNationality' => 'Sahrawian', 'country_arNationality' => 'صحراوي'],
            ['code' => 'YE', 'country_enName' => 'Yemen', 'country_arName' => 'اليمن', 'country_enNationality' => 'Yemeni', 'country_arNationality' => 'يمني'],
            ['code' => 'ZM', 'country_enName' => 'Zambia', 'country_arName' => 'زامبيا', 'country_enNationality' => 'Zambian', 'country_arNationality' => 'زامبياني'],
            ['code' => 'ZW', 'country_enName' => 'Zimbabwe', 'country_arName' => 'زمبابوي', 'country_enNationality' => 'Zimbabwean', 'country_arNationality' => 'زمبابوي'],
        ];

        DB::table('countries')->insert($countries);
    }
}
